spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:192.168.10.14}:${MARIADB_PORT:20191}/dcim
    username: ${DB_USER:dcim}
    password: ${DB_PASS:dcim123}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties.hibernate:
      format_sql: true
      use_sql_comment: true
      jdbc.time_zone: UTC
    open-in-view: false

management:
  influx:
    metrics:
      export:
        enabled: false

influx:
  enabled: ${INFLUX_ENABLED:true}
  url: ${INFLUX_URL:http://localhost:8086}
  token: ${INFLUX_TOKEN:vHGms79bf5fZDmppiP3TlhcHt1inFUmQmCg7URBv5FFnoY5vxDMsTgCrRTp4eWGWST5bbDObuwLAN2UF82YWgQ==}
  org: ${INFLUX_ORG:vivans}
  bucket: ${INFLUX_BUCKET:dcim}
  measurement: ${INFLUX_MEASUREMENT:dcim_sensor}
