CREATE TABLE IF NOT EXISTS `device_asset_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` int(11) NOT NULL,
  `action` varchar(30) NOT NULL COMMENT 'ASSET_UPDATED/STATUS_CHANGED',
  `actor_name` varchar(100) DEFAULT NULL COMMENT '변경 사용자 또는 시스템',
  `reason` varchar(1000) DEFAULT NULL COMMENT '상태 변경 사유',
  `previous_asset_code` varchar(100) DEFAULT NULL,
  `current_asset_code` varchar(100) DEFAULT NULL,
  `previous_serial_number` varchar(200) DEFAULT NULL,
  `current_serial_number` varchar(200) DEFAULT NULL,
  `previous_status_code` varchar(100) DEFAULT NULL,
  `previous_status_name` varchar(255) DEFAULT NULL,
  `current_status_code` varchar(100) DEFAULT NULL,
  `current_status_name` varchar(255) DEFAULT NULL,
  `previous_enabled` tinyint(1) DEFAULT NULL,
  `current_enabled` tinyint(1) DEFAULT NULL,
  `created_dt` timestamp(6) NULL DEFAULT current_timestamp(6),
  `updated_dt` timestamp(6) NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `idx_device_asset_history_device_dt` (`device_id`, `created_dt`),
  CONSTRAINT `fk_device_asset_history_device` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='장비 자산 정보 및 운영 상태 변경 이력';
